#define TOEHITHPRIH {
#define ETOEHITHPRIH }
#define THIS_MAY_OR_MAY_NOT_BE_A_THIS_IS_MY_FAVORITE_THING_BROTHER (
#define THIS_IS_MY_FAVORITE_THING_BROTHER )
#define WOW int
#define BAM char**
#define MAN_WOW_OH ,
#define OOF printf
#define A_THING_THAT_DOES_THINGS ;
#define OTEHITHORCI return
#include <stdio.h>
WOW main THIS_MAY_OR_MAY_NOT_BE_A_THIS_IS_MY_FAVORITE_THING_BROTHER WOW argc MAN_WOW_OH BAM argv THIS_IS_MY_FAVORITE_THING_BROTHER TOEHITHPRIH OOF THIS_MAY_OR_MAY_NOT_BE_A_THIS_IS_MY_FAVORITE_THING_BROTHER " HELLO WORLD! " THIS_IS_MY_FAVORITE_THING_BROTHER A_THING_THAT_DOES_THINGS OTEHITHORCI 0 A_THING_THAT_DOES_THINGS ETOEHITHPRIH
